#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate kids_youth_content.json with abundant story units."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "packages" / "core" / "data" / "kids_youth_content.json"

KIDS = [
    ("k01", "🌍", "神說：要有光！", "Let There Be Light!", 1, 1, "創世記",
     "一開始，什麼都沒有。神說：「要有光！」就亮了！神看光是好的。",
     "At first it was dark. God said, Let there be light! And there was light. God saw it was good.",
     "神創造的世界開始發光。", "God's world began to shine.",
     "今晚睡覺前，感謝神給我們白天和黑夜。", "Thank God for day and night before you sleep."),
    ("k02", "🌈", "挪亞的大方舟", "Noah's Big Ark", 1, 6, "創世記",
     "挪亞聽神的話，造了一艘大船。動物們成雙成對上船。雨停後，天空出現彩虹，是神與人的約定。",
     "Noah obeyed God and built a big ark. Animals came two by two. After the rain, a rainbow appeared.",
     "彩虹提醒神守約愛我們。", "The rainbow reminds us God keeps promises.",
     "畫一道彩虹送給家人。", "Draw a rainbow for your family."),
    ("k03", "⭐", "亞伯拉罕數星星", "Abraham Counts Stars", 1, 15, "創世記",
     "神帶亞伯拉罕看夜空：你的後代要多如星星。他雖然年老，仍然相信神。",
     "God showed Abraham the stars: your family will be countless. Abraham trusted God.",
     "信神的人，神也為他預備。", "God prepares for those who trust Him.",
     "今晚看看天空，數三顆星並禱告。", "Count three stars tonight and pray."),
    ("k04", "🎨", "約瑟的彩色衣", "Joseph's Colorful Coat", 1, 37, "創世記",
     "爸爸給約瑟一件彩衣。哥哥們嫉妒，但神與約瑟同在，後來他成了拯救家人的人。",
     "Joseph got a colorful coat. His brothers were jealous, but God was with Joseph to save his family.",
     "神能變壞事為好事。", "God can turn hard things into good.",
     "稱讚一位家人一個優點。", "Compliment someone in your family."),
    ("k05", "🧺", "摩西在蘆葦叢", "Baby Moses in the Reeds", 2, 2, "出埃及記",
     "小摩西放在籃裡，漂在河邊。公主發現他，神保守這個嬰孩長大，將來帶領百姓。",
     "Baby Moses floated in a basket. A princess found him. God kept him safe to lead His people.",
     "神看顧弱小的人。", "God cares for the small and weak.",
     "為比你小的孩子禱告。", "Pray for a younger child today."),
    ("k06", "🌊", "紅海分開的路", "Path Through the Sea", 2, 14, "出埃及記",
     "百姓被追趕，神使海分開，大家走乾地過去！神為祂的子民開路。",
     "People were chased. God split the sea so they walked on dry ground!",
     "神為信祂的人開路。", "God opens a way for those who trust Him.",
     "唱一首你喜歡的詩歌給神。", "Sing a song to God."),
    ("k07", "🎯", "大衛與歌利亞", "David and Goliath", 9, 17, "撒母耳記上",
     "少年大衛用五顆石子，靠神打敗巨人。他說：戰場在耶和華手裡！",
     "Young David defeated a giant with a sling. The battle belongs to the Lord!",
     "神用的不是大小，而是信心。", "God looks at faith, not size.",
     "做一件需要勇氣的小事。", "Do one small brave thing today."),
    ("k08", "🐋", "約拿與大魚", "Jonah and the Big Fish", 32, 1, "約拿書",
     "約拿不想聽神，坐船逃跑。暴風中他被扔下海，大魚吞了他。他在魚裡禱告，神給他第二次機會。",
     "Jonah ran from God. A big fish swallowed him. He prayed inside, and God gave him another chance.",
     "神給願意回轉的人機會。", "God gives second chances.",
     "向神說一件你願意改正的事。", "Tell God one thing you want to do better."),
    ("k09", "👶", "耶穌在馬槽", "Baby Jesus in the Manger", 40, 2, "馬太福音",
     "耶穌生在一個簡單的馬槽，卻是救主！天使報喜訊：在城裡為你們生了救主。",
     "Jesus was born in a manger. Angels said: A Savior is born for you!",
     "最大的禮物是耶穌。", "The best gift is Jesus.",
     "寫一張感恩卡給家人。", "Write a thank-you note to family."),
    ("k10", "⛵", "耶穌平風浪", "Jesus Calms the Storm", 41, 4, "馬可福音",
     "門徒在船上害怕。耶穌起來說：風止了吧！風浪就停了。耶穜說：你們的信心在哪裡？",
     "Disciples were scared on the boat. Jesus said, Quiet! Be still! The storm stopped.",
     "有耶穌同行，不用怕。", "With Jesus, we don't need to fear.",
     "害怕時，深呼吸並說：主與我同在。", "When afraid, breathe and say: Jesus is with me."),
    ("k11", "❤️", "好撒瑪利亞人", "Good Samaritan", 42, 10, "路加福音",
     "有人受傷倒地，很多人路過。一個外國人停下來幫助他、包紮他。耶穌說：去照樣行。",
     "A man was hurt. Many walked by. A Samaritan stopped to help. Go and do likewise.",
     "愛人如己要付出行動。", "Love your neighbor with action.",
     "幫助一個需要幫助的人。", "Help someone who needs help."),
    ("k12", "🌳", "撒該爬樹", "Zacchaeus Climbs a Tree", 42, 19, "路加福音",
     "撒該個子小，爬樹看耶穌。耶穌說：下來，今天我要去你家！撒該快樂地接待祂。",
     "Short Zacchaeus climbed a tree. Jesus said, Come down! I'm coming to your house!",
     "耶穌願意來到我們中間。", "Jesus wants to be with us.",
     "邀請家人一起讀一節經文。", "Read one verse with your family."),
    ("k13", "🐑", "失喪的羊", "The Lost Sheep", 42, 15, "路加福音",
     "牧人有百隻羊，失去一隻就去找，找到了就歡喜。天父也這樣找失喪的人。",
     "A shepherd leaves ninety-nine to find one lost sheep. Heaven rejoices when one is found.",
     "你在天父眼中很寶貴。", "You are precious to God.",
     "對一位朋友說：你是重要的。", "Tell a friend: you matter."),
    ("k14", "🍞", "五餅二魚", "Five Loaves and Two Fish", 43, 6, "約翰福音",
     "小男孩拿出五餅二魚，耶穌祝福，餵飽了五千人！小小獻上，神能做多大的事。",
     "A boy gave five loaves and two fish. Jesus blessed them and fed thousands!",
     "小小的給，神能放大。", "Small gifts, big miracles.",
     "把你有的東西分享一點給別人。", "Share something you have."),
    ("k15", "✨", "空墓與復活", "Empty Tomb!", 43, 20, "約翰福音",
     "耶穌死後被放在 tomb，第三天復活了！天使說：祂不在這裡，祂復活了！",
     "Jesus died and was buried. On the third day He rose! He is not here—He is alive!",
     "耶穌活著，給我們新生命。", "Jesus is alive and gives us new life.",
     "大聲說：主復活了！", "Say aloud: Jesus is risen!"),
    ("k16", "🦁", "但以理在獅子坑", "Daniel in the Lions' Den", 27, 6, "但以理書",
     "但以理每天禱告，被扔進獅子坑，神關閉獅子的口！他沒有受傷。",
     "Daniel prayed every day. In the lions' den, God shut the lions' mouths!",
     "持續禱告的人，神保守。", "God protects those who pray.",
     "今天固定一個禱告時間。", "Set a prayer time today."),
    ("k17", "👑", "以斯帖的勇氣", "Brave Queen Esther", 17, 4, "以斯帖記",
     "以斯帖王后為百姓冒險見王：「我若死就死吧！」神使用她拯救族人。",
     "Queen Esther risked her life: If I perish, I perish! God used her to save her people.",
     "為別人站出來需要勇氣。", "Standing up for others takes courage.",
     "為一位朋友禱告。", "Pray for a friend."),
    ("k18", "🤝", "路得和拿俄米", "Ruth and Naomi", 8, 1, "路得記",
     "路得對婆婆說：你的神就是我的神。她勤勞、忠誠，神賜福給她。",
     "Ruth said to Naomi: Your God will be my God. God blessed her loyalty.",
     "忠誠與 kindness 蒙福。", "Loyalty and kindness bring blessing.",
     "幫忙做一件家務。", "Help with one chore at home."),
    ("k19", "🏠", "浪子的回家", "The Prodigal Son", 42, 15, "路加福音",
     "小兒子離家揮霍，餓了想回家。爸爸跑出去擁抱他：我們歡慶吧！",
     "The son wasted everything and came home hungry. His father ran to hug him.",
     "天父永遠歡迎回家的人。", "Our Father always welcomes us home.",
     "對家人說：我愛你。", "Tell your family: I love you."),
    ("k20", "🎁", "四寶：信望愛", "Faith, Hope, Love", 46, 13, "哥林多前書",
     "保羅說：如今常存的有信、有望、有愛，其中最大的是愛。這是信仰四寶的寶藏！",
     "Faith, hope, and love remain—but the greatest is love. Treasure of our faith!",
     "愛是跑完路程的力量。", "Love helps us finish the race.",
     "向一個人說鼓勵的話。", "Encourage someone with words."),
]

YOUTH = [
    ("y01", "🚀", "開始這趟旅程", "Start the Journey", 41, 1, "馬可福音",
     "馬可福音節奏快，像一部行動片。耶穌開始傳天國的福音，呼召門徒：來跟從我！",
     "Mark moves fast like an action story. Jesus preaches God's kingdom and calls disciples.",
     "跟隨耶穌，人生有方向。", "Following Jesus gives direction.",
     "寫下本週你想讓神幫助的一件事。", "Write one thing you want God to help with this week."),
    ("y02", "💧", "受洗與身份", "Baptism and Identity", 41, 1, "馬可福音",
     "耶穌受洗，天父說：這是我的愛子。你的身份也是：被愛的兒女。",
     "At baptism the Father said: This is my beloved Son. You are God's beloved too.",
     "身份來自神，不是來自成績。", "Identity comes from God, not grades.",
     "列出三個你是誰（神所造的）。", "List three truths about who you are."),
    ("y03", "📖", "天國好像...", "The Kingdom Is Like...", 40, 13, "馬太福音",
     "耶穜用比喻：天國像芥菜種、像寶藏、像撒網。想想：神國如何在你生活中長大？",
     "Jesus taught with parables. How might God's kingdom grow in your life?",
     "小開始，也能有大影響。", "Small starts can have big impact.",
     "分享比喻給一位朋友。", "Share one parable with a friend."),
    ("y04", "🙏", "主禱文", "The Lord's Prayer", 40, 6, "馬太福音",
     "耶穜教門徒禱告：我們在天上的父…願你的國降臨。這是每個跑者的加油禱告。",
     "Our Father in heaven… Your kingdom come. A prayer for every runner on this journey.",
     "禱告是與父對話。", "Prayer is talking with Father God.",
     "用主禱文為家人禱告一次。", "Pray the Lord's Prayer for your family."),
    ("y05", "⚡", "十個長大的人", "Ten Lepers Healed", 42, 17, "路加福音",
     "十個長大的人得醫治，只有一人回來感謝。感恩是跑完路程的秘訣。",
     "Ten were healed; one returned to thank Jesus. Gratitude keeps us running.",
     "感恩讓心更輕。", "Thankfulness lightens the heart.",
     "寫三張感恩便條。", "Write three thank-you notes."),
    ("y06", "🔥", "五旬節的能力", "Power at Pentecost", 44, 2, "使徒行傳",
     "聖靈降臨，門徒得能力見證。你不需要完美，只需要願意被神使用。",
     "The Spirit came; disciples received power to witness. Willing beats perfect.",
     "神使用願意的人。", "God uses willing people.",
     "為一位未信主的朋友禱告。", "Pray for one friend who doesn't know Jesus."),
    ("y07", "💎", "因信稱義", "Justified by Faith", 45, 3, "羅馬書",
     "沒有人靠行為完全，我們因信耶穌而與神和好。這是跑道的起點：恩典。",
     "We are made right with God by faith in Jesus. Grace is the starting line.",
     "恩典是起跑的力。", "Grace powers the start.",
     "記下一節羅馬書 3:23-24。", "Memorize Romans 3:23-24."),
    ("y08", "🛡️", "全副軍裝", "Armor of God", 49, 6, "以弗所書",
     "真理、公義、福音、信德、救恩、聖靈的 sword。每天穿上，面對學校與試探。",
     "Put on truth, righteousness, gospel, faith, salvation, Spirit's word daily.",
     "屬靈軍裝是每日穿戴。", "Spiritual armor is daily wear.",
     "選一項軍裝，今天實踐。", "Practice one piece of armor today."),
    ("y09", "🌱", "果子聖靈", "Fruit of the Spirit", 48, 5, "加拉太書",
     "愛、喜樂、和平…不是靠硬撐，是與耶穌同行自然結出的果子。",
     "Love, joy, peace… fruit of walking with Jesus, not forcing ourselves.",
     "與神同行，生命有果子。", "Walk with God; fruit will show.",
     "今天刻意做一件「和平」的事。", "Do one peacemaking act today."),
    ("y10", "🏃", "跑當跑的路", "Run Your Race", 55, 4, "提摩太後書",
     "保羅說：當跑的路我已跑盡。你的跑道是獨特的，專心跑，不要比較。",
     "I have finished my race. Your track is unique—run it without comparing.",
     "專心你的跑道。", "Focus on your own lane.",
     "設定本週一個讀經小目標。", "Set one small reading goal this week."),
    ("y11", "🤔", "所羅門的智慧", "Solomon's Wisdom", 20, 1, "箴言",
     "箴言充滿生活智慧：舌頭、朋友、金錢。每天讀一節，像補給站加油。",
     "Proverbs is practical: words, friends, money. One verse a day fuels you.",
     "智慧從每日一節開始。", "Wisdom starts with one verse daily.",
     "讀箴言 3:5-6 並分享。", "Read Proverbs 3:5-6 and share."),
    ("y12", "🎵", "詩篇的哭與笑", "Psalms: Cry and Praise", 19, 23, "詩篇",
     "詩篇 23：耶和華是我的牧者。你可以向神說真話—包括害怕和感恩。",
     "The Lord is my shepherd. Psalms let you be honest with God—fear and thanks.",
     "向神誠實，祂仍作牧者。", "Be honest; God still shepherds.",
     "用詩篇 23 寫一段短禱告。", "Pray briefly using Psalm 23."),
    ("y13", "🔭", "以賽亞的異象", "Isaiah's Vision", 23, 6, "以賽亞書",
     "以賽亞看見聖潔的神，說：我在這裡，請差遣我！少年也能回應呼召。",
     "Isaiah saw God's holiness: Here am I, send me! Youth can answer God's call.",
     "少年也能被差遣。", "Young people can be sent.",
     "問：神，你要我用什麼服事？", "Ask God: how can I serve?"),
    ("y14", "🌊", "啟示錄的盼望", "Hope in Revelation", 66, 21, "啟示錄",
     "新天新地，神與人同住，擦去一切眼淚。長跑有終點，且是美好的終點。",
     "New heaven and earth—God with us, no more tears. The race ends well.",
     "終點有盼望。", "The finish line is hope.",
     "寫下你對「新造世界」的一個想像。", "Write one hope for the new creation."),
    ("y15", "🏆", "同跑隊凱旋", "Squad Finish Line", 44, 1, "使徒行傳",
     "早期教會一起興起。邀請朋友同跑：你跑我追，一起歡呼過終點！",
     "The early church ran together. Invite friends—chase each other to the finish!",
     "信仰是一起跑。", "Faith is a team sport.",
     "組隊邀請一位朋友本週一起讀。", "Invite one friend to read with you this week."),
]

PALETTES = [
    ["#FF6B6B", "#FFE66D", "#4ECDC4"],
    ["#A78BFA", "#F472B6", "#FBBF24"],
    ["#34D399", "#60A5FA", "#F97316"],
    ["#FB7185", "#818CF8", "#2DD4BF"],
    ["#F59E0B", "#EC4899", "#8B5CF6"],
]


def game_for(idx, title_zh):
    words = title_zh.replace("！", "").replace("？", "")[:4]
    return {
        "type": "pick",
        "questionZh": f"「{title_zh}」這個故事告訴我們什麼？",
        "questionEn": "What does this story teach us?",
        "optionsZh": ["神與我們同在", "只要靠自己", "不用理會別人"],
        "optionsEn": ["God is with us", "Only myself", "Ignore others"],
        "answerIndex": 0,
        "wordPuzzleZh": words if len(words) >= 2 else "信望愛",
    }


def build():
    units = []
    for i, row in enumerate(KIDS):
        uid, emoji, title, title_en, b, c, book, story, story_en, one, one_en, act, act_en = row
        pal = PALETTES[i % len(PALETTES)]
        g = game_for(i, title)
        units.append({
            "unitId": uid,
            "track": "kids_story",
            "order": i + 1,
            "titleZh": title,
            "titleEn": title_en,
            "heroEmoji": emoji,
            "colors": {"primary": pal[0], "secondary": pal[1], "accent": pal[2]},
            "bookId": b,
            "chapter": c,
            "bookLabelZh": book,
            "storyZh": story,
            "storyEn": story_en,
            "oneLineZh": one,
            "oneLineEn": one_en,
            "actionZh": act,
            "actionEn": act_en,
            "minutes": 5 + (i % 3),
            "sticker": {"id": f"st_{uid}", "nameZh": f"{emoji} 貼紙", "nameEn": f"{emoji} Sticker", "emoji": emoji},
            "game": g,
            "supplyUrl": "https://bible100.lovestoblog.com/languages/index_cn.html",
        })
    for i, row in enumerate(YOUTH):
        uid, emoji, title, title_en, b, c, book, story, story_en, one, one_en, act, act_en = row
        pal = PALETTES[(i + 2) % len(PALETTES)]
        g = game_for(i, title)
        units.append({
            "unitId": uid,
            "track": "youth_quest",
            "order": i + 1,
            "titleZh": title,
            "titleEn": title_en,
            "heroEmoji": emoji,
            "colors": {"primary": pal[0], "secondary": pal[1], "accent": pal[2]},
            "bookId": b,
            "chapter": c,
            "bookLabelZh": book,
            "storyZh": story,
            "storyEn": story_en,
            "oneLineZh": one,
            "oneLineEn": one_en,
            "actionZh": act,
            "actionEn": act_en,
            "minutes": 8 + (i % 3),
            "sticker": {"id": f"st_{uid}", "nameZh": f"{emoji} 勳章", "nameEn": f"{emoji} Badge", "emoji": emoji},
            "game": g,
            "supplyUrl": "https://bible100.lovestoblog.com/languages/index_cn.html",
        })

    payload = {
        "version": "1.0",
        "schema": "kids_youth_content",
        "tracks": [
            {"id": "kids_story", "nameZh": "開心故事跑", "nameEn": "Happy Story Run", "emoji": "🦁", "unitCount": 20},
            {"id": "youth_quest", "nameZh": "青春闖關跑", "nameEn": "Youth Quest Run", "emoji": "🚀", "unitCount": 15},
        ],
        "units": units,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"Wrote {OUT} with {len(units)} units")


if __name__ == "__main__":
    build()
