/** Certificate metadata — PDF bytes generated by Cloud Function in production. */
export interface CertificatePayload {
  userId: string;
  displayName: string;
  churchName: string;
  issuedAt: string;
  tracksCompleted: string[];
  locale: 'zh-Hant' | 'en';
}

export function certificateTitle(locale: CertificatePayload['locale']): string {
  return locale === 'zh-Hant' ? '聖經三跑道讀經完成證書' : 'Bible Three-Track Completion Certificate';
}

export function certificateBody(payload: CertificatePayload): string {
  const tracks = payload.tracksCompleted.join(', ');
  if (payload.locale === 'zh-Hant') {
    return `茲證明 ${payload.displayName} 已完成舊約前部、舊約後部與新約讀經跑道（${tracks}），特發此證。`;
  }
  return `This certifies that ${payload.displayName} has completed OT Front, OT Back, and NT reading tracks (${tracks}).`;
}

/** Plain-text PDF placeholder content for Functions html-pdf pipeline */
export function certificateHtml(payload: CertificatePayload): string {
  return `<!DOCTYPE html><html><body style="font-family:serif;text-align:center;padding:48px">
<h1>${certificateTitle(payload.locale)}</h1>
<p>${certificateBody(payload)}</p>
<p>${payload.churchName}</p>
<p>${payload.issuedAt}</p>
</body></html>`;
}
