/**
 * 操作說明 · 本站理念 — 四語內容 SSOT（小白招待處語氣）
 */
(function (global) {
  var HOWTO = {
    'zh-Hant': {
      title: '怎麼用',
      lead: '像朋友帶你走一遍。每天只要幾分鐘，不用背課、不用考試。',
      whatTitle: '這是什麼？',
      whatBody: '聖經跑道陪你每天讀一點聖經：系統選好經段，讀完打卡，偶爾看看同跑隊伍。不是考試，也不是考勤。',
      flowTitle: '四步就夠了',
      steps: [
        { icon: '☀️', title: '點「今日關卡」', text: '每天約 5 分鐘。系統幫你選好今天要讀哪一段。' },
        { icon: '📖', title: '讀經文', text: '不用自己找書卷章節，按「開始讀經」就好。' },
        { icon: '✅', title: '讀完打個勾', text: '領取今日一句應用 + 30 秒禱告，帶進生活。' },
        { icon: '🤝', title: '偶爾看看同跑隊伍', text: '知道還有人在陪你，不排名、不攀比。' },
      ],
      reliefTitle: '不小心斷更了？沒關係',
      reliefBody: '如果你忙了好幾天忘了讀，請不要愧疚。這不是考勤，是你給自己的靈魂補給。我們不會懲罰你，也不會累積虧欠感。打開頁面，點「今日關卡」，從今天重新出發就好。',
      reliefBtn: '去今日關卡 →',
      microTitle: '今天很累？試試精華版',
      microBody: '只要 1～3 分鐘：在首頁點「今日關卡」，或改走「100 金句」讀一節短經文，一樣可以打卡、一樣算數。',
      restTitle: '想休息幾天？可以',
      restBody: '你不需要跟任何人報備。想停就停，回來時我們只會說：歡迎回來，從今日關卡繼續吧。',
      shortcutTitle: '卡住了？點這裡',
      shortcuts: [
        { icon: '💬', label: '讀不懂 → 牧養問答', href: 'ai-qna.html', desc: '用簡單、合乎正統信仰的方式解釋背景與重點；重要仍請問牧師' },
        { icon: '🏃', label: '覺得孤單 → 同跑隊伍', href: 'pacing.html', desc: '留一句今日亮光或代禱' },
        { icon: '📊', label: '想看進度 → 智慧導師', href: 'ai-tutor.html', desc: '本週讀了多少、下週建議' },
      ],
      faqTitle: '常見問題',
      faqs: [
        { q: '要註冊嗎？', a: '不用。進度存在你自己的瀏覽器裡。' },
        { q: '我不小心斷更了怎麼辦？', a: '沒關係，直接點「今日關卡」繼續。不扣分、不罵人。' },
        { q: '一定要讀完整章嗎？', a: '不必有壓力。今日關卡或金句短讀也可以。' },
        { q: '怎麼開完整聖經？', a: '請用「打開聖經跑道.bat」或本機網址開啟，不要直接雙擊 html 檔。' },
        { q: '為什麼創世記 1–2 章對整本聖經這麼重要？', a: '它告訴我們神創造、人有尊嚴、罪進入世界——整本聖經的大故事從這裡展開。' },
        { q: '舊約律法和今天的生活有什麼關係？', a: '律法顯出神的聖潔與人的需要；在基督裡我們靠恩典，但仍從律法學習愛神愛人。細節可問牧師或看牧養問答。' },
      ],
      rememberTitle: '只記三件事',
      remember: [
        '每天：今日關卡',
        '讀完：打卡',
        '不懂：牧養問答（白話解經，不取代牧師）',
      ],
      cta: '我準備好了，開始今日關卡 →',
      ideaLink: '想了解為什麼做這個？看本站理念',
    },
    en: {
      title: 'How to use',
      lead: 'A friend-style walkthrough. A few minutes a day—no exams, no memory tests.',
      whatTitle: 'What is this?',
      whatBody: 'Bible Journey helps you read Scripture a little each day: we pick the passage, you check in, and you can peek at your squad. Not a test, not roll call.',
      flowTitle: 'Four steps—that\'s it',
      steps: [
        { icon: '☀️', title: 'Tap Today\'s challenge', text: '~5 minutes. We pick today\'s passage for you.' },
        { icon: '📖', title: 'Read', text: 'No hunting for book/chapter—just tap Start reading.' },
        { icon: '✅', title: 'Check in when done', text: 'Get one life line + a short prayer for today.' },
        { icon: '🤝', title: 'Peek at your squad sometimes', text: 'You\'re not alone. No leaderboard, no shame.' },
      ],
      reliefTitle: 'Missed a few days? You\'re welcome back',
      reliefBody: 'If life got busy, please don\'t carry guilt. This isn\'t attendance tracking—it\'s soul care. We won\'t punish you or pile on "debt." Open the app, tap Today\'s challenge, and start fresh today.',
      reliefBtn: 'Go to Today\'s challenge →',
      microTitle: 'Exhausted today? Try the lite path',
      microBody: '1–3 minutes: Today\'s challenge, or Golden Verses for one short passage. It still counts.',
      restTitle: 'Need a break? That\'s allowed',
      restBody: 'You don\'t owe anyone an explanation. When you return, we simply say: welcome back—pick up from Today.',
      shortcutTitle: 'Stuck? Tap here',
      shortcuts: [
        { icon: '💬', label: 'Confused → Q&A', href: 'ai-qna.html', desc: 'Plain, orthodox-friendly notes on context; pastors still lead' },
        { icon: '🏃', label: 'Lonely → Squad', href: 'pacing.html', desc: 'Share a highlight or prayer request' },
        { icon: '📊', label: 'Progress → Mentor', href: 'ai-tutor.html', desc: 'Weekly recap and next steps' },
      ],
      faqTitle: 'FAQ',
      faqs: [
        { q: 'Sign up?', a: 'No. Progress stays on your device.' },
        { q: 'I broke my streak—now what?', a: 'No problem. Tap Today\'s challenge. No penalty.' },
        { q: 'Must I finish a whole chapter?', a: 'No pressure. Short reads count too.' },
        { q: 'Full Bible not loading?', a: 'Use the local server / .bat file, not file://.' },
        { q: 'Why do Genesis 1–2 matter for the whole Bible?', a: 'They introduce creation, human dignity, and sin—the big story starts here.' },
        { q: 'What about Old Testament law today?', a: 'The law shows God\'s holiness and our need; in Christ we live by grace while learning to love God and neighbor. Ask your pastor for details.' },
      ],
      rememberTitle: 'Remember only three things',
      remember: [
        'Daily: Today\'s challenge',
        'Done: check in',
        'Stuck: Q&A (plain notes—not replacing your pastor)',
      ],
      cta: 'I\'m ready—start Today →',
      ideaLink: 'Why we built this? Read our vision',
    },
    vi: {
      title: 'Cách dùng',
      lead: 'Như bạn bè dẫn bạn đi. Mỗi ngày vài phút—không thi, không thuộc lòng gắt gao.',
      whatTitle: 'Đây là gì?',
      whatBody: 'Hành trình Kinh Thánh giúp bạn đọc một chút mỗi ngày: hệ thống chọn đoạn, bạn check-in, thỉnh thoảng xem đội chạy. Không phải thi, không điểm danh.',
      flowTitle: 'Chỉ bốn bước',
      steps: [
        { icon: '☀️', title: 'Bấm Thử thách hôm nay', text: 'Khoảng 5 phút. Hệ thống chọn đoạn Kinh cho bạn.' },
        { icon: '📖', title: 'Đọc', text: 'Không cần tự tìm sách/chương—bấm Bắt đầu đọc.' },
        { icon: '✅', title: 'Check-in khi xong', text: 'Nhận một câu ứng dụng + lời cầu ngắn.' },
        { icon: '🤝', title: 'Thỉnh thoảng xem đội', text: 'Có người đồng hành. Không xếp hạng.' },
      ],
      reliefTitle: 'Quên vài ngày? Không sao cả',
      reliefBody: 'Bận rộn là chuyện thường—đừng tự trách. Đây không phải chấm công, mà là nuôi dưỡng đời sống linh hồn. Không phạt, không ghi nợ. Mở trang, bấm Thử thách hôm nay, bắt đầu lại từ hôm nay.',
      reliefBtn: 'Đến Thử thách hôm nay →',
      microTitle: 'Mệt hôm nay? Đọc bản rút gọn',
      microBody: '1–3 phút: Thử thách hôm nay hoặc Câu vàng. Vẫn tính là đã đọc.',
      restTitle: 'Muốn nghỉ vài ngày? Được',
      restBody: 'Bạn không cần xin phép ai. Khi quay lại, chúng tôi chỉ nói: chào mừng trở lại.',
      shortcutTitle: 'Bí quá? Bấm đây',
      shortcuts: [
        { icon: '💬', label: 'Không hiểu → Hỏi đáp', href: 'ai-qna.html', desc: 'Giải thích đơn giản, phù hợp đức tin chính thống; vẫn hỏi mục sư' },
        { icon: '🏃', label: 'Cô đơn → Đội chạy', href: 'pacing.html', desc: 'Chia sẻ điểm sáng hoặc cầu nguyện' },
        { icon: '📊', label: 'Tiến độ → Cố vấn', href: 'ai-tutor.html', desc: 'Tổng kết tuần' },
      ],
      faqTitle: 'Câu hỏi thường gặp',
      faqs: [
        { q: 'Cần đăng ký?', a: 'Không. Tiến độ lưu trên máy bạn.' },
        { q: 'Đứt chuỗi ngày?', a: 'Không sao. Bấm Thử thách hôm nay là được.' },
        { q: 'Phải đọc hết chương?', a: 'Không ép. Đọc ngắn cũng được.' },
        { q: 'Không tải đủ Kinh Thánh?', a: 'Dùng máy chủ cục bộ / file .bat.' },
        { q: 'Vì sao Sáng thế 1–2 quan trọng với cả Kinh Thánh?', a: 'Nói về sáng tạo, phẩm giá con người, tội lỗi—câu chuyện lớn bắt đầu từ đây.' },
        { q: 'Luật Cựu Ước và đời sống hôm nay?', a: 'Luật tỏ sự thánh của Chúa và nhu cầu của ta; trong Christ ta sống bởi ân điển và học yêu Chúa, yêu người. Hỏi mục sư để đi sâu.' },
      ],
      rememberTitle: 'Chỉ nhớ ba điều',
      remember: [
        'Hàng ngày: Thử thách',
        'Xong: check-in',
        'Bí: Hỏi đáp (giải thích đơn giản—không thay mục sư)',
      ],
      cta: 'Bắt đầu hôm nay →',
      ideaLink: 'Vì sao có trang này? Xem tầm nhìn',
    },
    id: {
      title: 'Cara pakai',
      lead: 'Seperti teman yang menemani. Beberapa menit sehari—tanpa ujian, tanpa hafalan paksa.',
      whatTitle: 'Apa ini?',
      whatBody: 'Perjalanan Alkitab menemani Anda membaca sedikit setiap hari: kami pilih bacaan, Anda check-in, sesekali lihat tim lari. Bukan ujian, bukan absensi.',
      flowTitle: 'Empat langkah saja',
      steps: [
        { icon: '☀️', title: 'Ketuk Tantangan hari ini', text: '~5 menit. Kami pilih bacaan untuk Anda.' },
        { icon: '📖', title: 'Baca', text: 'Tidak perlu cari kitab/pasal—ketuk Mulai baca.' },
        { icon: '✅', title: 'Check-in selesai', text: 'Satu kalimat aplikasi + doa singkat.' },
        { icon: '🤝', title: 'Sesekali lihat tim', text: 'Anda tidak sendirian. Tanpa peringkat.' },
      ],
      reliefTitle: 'Terlewat beberapa hari? Boleh kembali',
      reliefBody: 'Sibuk itu wajar—jangan menanggung rasa bersalah. Ini bukan absensi, ini perawatan jiwa. Tidak ada hukuman atau "utang". Buka halaman, ketuk Tantangan hari ini, mulai lagi hari ini.',
      reliefBtn: 'Ke Tantangan hari ini →',
      microTitle: 'Lelah hari ini? Versi ringkas',
      microBody: '1–3 menit: Tantangan hari ini atau Ayat emas. Tetap dihitung.',
      restTitle: 'Butuh istirahat? Silakan',
      restBody: 'Anda tidak perlu izin siapa pun. Saat kembali, kami hanya katakan: selamat datang kembali.',
      shortcutTitle: 'Buntu? Ketuk di sini',
      shortcuts: [
        { icon: '💬', label: 'Bingung → Tanya jawab', href: 'ai-qna.html', desc: 'Penjelasan sederhana sesuai iman ortodoks; gembala tetap memimpin' },
        { icon: '🏃', label: 'Kesepian → Tim lari', href: 'pacing.html', desc: 'Bagikan sorotan atau doa' },
        { icon: '📊', label: 'Progres → Mentor', href: 'ai-tutor.html', desc: 'Ringkasan mingguan' },
      ],
      faqTitle: 'Pertanyaan umum',
      faqs: [
        { q: 'Perlu daftar?', a: 'Tidak. Progres di perangkat Anda.' },
        { q: 'Putus beruntun?', a: 'Tidak masalah. Ketuk Tantangan hari ini.' },
        { q: 'Harus selesai satu pasal?', a: 'Tanpa tekanan. Bacaan pendek juga sah.' },
        { q: 'Alkitab tidak lengkap?', a: 'Gunakan server lokal / file .bat.' },
        { q: 'Mengapa Kejadian 1–2 penting untuk seluruh Alkitab?', a: 'Memperkenalkan penciptaan, martabat manusia, dan dosa—kisah besar dimulai di sini.' },
        { q: 'Hukum Perjanjian Lama dan hidup hari ini?', a: 'Hukum menunjukkan kekudusan Allah dan kebutuhan kita; dalam Kristus kita hidup oleh kasih karunia sambil belajar mengasihi. Tanya gembala untuk detail.' },
      ],
      rememberTitle: 'Ingat tiga hal',
      remember: [
        'Harian: Tantangan',
        'Selesai: check-in',
        'Bingung: Tanya jawab (catatan sederhana—bukan pengganti gembala)',
      ],
      cta: 'Mulai hari ini →',
      ideaLink: 'Mengapa ada halaman ini? Baca visi kami',
    },
  };

  var IDEA = {
    'zh-Hant': {
      title: '為什麼做',
      lead: '嗨，歡迎你。若你是被人推薦來的，我們想先說：這裡不嚴肅到讓人害怕。',
      p1: '我們知道打開「聖經」有時會緊張——怕讀不懂、怕做不到、怕牧師問進度。聖經跑道想做的，是每天給自己一點安靜，不是多一項考勤。',
      p2: '這裡不要求你背誦聖經，不要求你考試。只希望你每天願意給自己 5 分鐘，讓神的話輕輕碰一下你的生活。',
      p3: '你不是一個人。跑道上都是還在學走路的人，互相鼓勵，讀得慢不會被淘汰，斷更也不會被罵。',
      bibleStoryTitle: '聖經有路線，不是零散金句',
      bibleStoryBody: '三十日計畫會帶你走過創造、墮落、救贖、教會與新天新地的大故事。關卡經段兼顧舊約與新約、敘事與書信、詩歌與智慧文，避免只讀斷章摘句。',
      versionsTitle: '譯本與多語',
      versionsBody: '繁體和合本、KJV、越南語 1934、印尼 AYT 等常用譯本並排，方便對照字義。四語並排不只是查字，也讓多語家庭、跨文化教會可以讀同一段經文。',
      busyTitle: '給忙碌的你',
      busyBody: '我們知道你很忙。所以設計了「微讀經」：5 分鐘的質，常常比硬撐 1 小時更好。累了就讀短一點，回來了就好。',
      promiseTitle: '我們的承諾',
      promises: [
        '詞彙太深？點牧養問答，我們用白話解釋。',
        '不想一個人讀？同跑隊伍可以留言、代禱，不排名。',
        'AI 只是草稿，重要的事請問牧師——我們不取代你的帶領者。',
        '進度在你自己的裝置上，我們不拿來比較誰讀得多。',
      ],
      notTitle: '我們刻意不做的事',
      notList: [
        '不做公開個人排行榜',
        '不用罪惡感逼你打卡',
        '不把 AI 當成權威教義',
      ],
      supplyTitle: '跑道與補給站',
      supplyBody: '聖經跑道 = 每天跑步的操場（習慣、打卡、陪伴）。Bible100 補給站 = 查經、工具、教材，需要時再去。不會也沒關係，從今日關卡就夠了。',
      supplyLink: '→ 前往 Bible100 補給站',
      supplyUrl: 'https://bible100.lovestoblog.com/languages/index_cn.html',
      leaderTitle: '給帶領者（老師／牧者）',
      leaderBody: '每個關卡含經文、應用金句與短禱告建議，可作主日學或小組預備。建議您先走一遍跑道，留意順序與神學重點，再配合自己的教學。我們不取代您的釋經權責。',
      deepenTitle: '想再往深處走？',
      deepenBody: '走完首批三十日後，若願意深入，可前往 Bible100 補給站查背景、書卷導論與延伸閱讀。跑道先幫你養成習慣，深度學習隨時可以加。',
      cta: '從今日關卡開始 →',
      howtoLink: '想看怎麼操作？',
    },
    en: {
      title: 'Why we built this',
      lead: 'Hi—if a friend sent you here, relax. This isn’t a stern classroom.',
      p1: 'Opening the Bible can feel heavy—fear of not understanding, not keeping up, or being judged. Bible Journey is a daily quiet moment, not a roll call.',
      p2: 'No memorization tests. No exams. Just an invitation to five minutes a day where God’s word can meet your real life.',
      p3: 'You’re not alone. We’re all beginners here. Slow readers aren’t eliminated; missed days aren’t shamed.',
      bibleStoryTitle: 'Scripture has a storyline',
      bibleStoryBody: 'The 30-day plan walks creation, fall, redemption, church, and new creation—not random quotes. Passages balance Old and New Testaments, narrative and letters, poetry and wisdom.',
      versionsTitle: 'Translations & languages',
      versionsBody: 'Traditional Chinese Union, KJV, Vietnamese 1934, Indonesian AYT, and more—side by side for families and multicultural churches reading the same text.',
      busyTitle: 'For busy people',
      busyBody: 'Five focused minutes often beat a guilty one-hour slog. Tired? Read shorter. Came back? That’s enough.',
      promiseTitle: 'Our promises',
      promises: [
        'Hard words? Q&A in plain language.',
        'Lonely? Squad notes and prayer—no ranks.',
        'AI is draft only; pastors still lead.',
        'Your progress stays on your device—we don’t compare people.',
      ],
      notTitle: 'What we won’t do',
      notList: [
        'No public leaderboards',
        'No guilt trips for missing days',
        'No AI as final doctrine',
      ],
      supplyTitle: 'Track vs supply station',
      supplyBody: 'Bible Journey = daily track (habit, check-in, companions). Bible100 = deeper study & tools when you need them. Starting with Today is enough.',
      supplyLink: '→ Bible100 supply station',
      supplyUrl: 'https://bible100.lovestoblog.com/languages/index_en.html',
      leaderTitle: 'For leaders (teachers / pastors)',
      leaderBody: 'Each challenge includes Scripture, an application line, and a short prayer—usable for Sunday school or small groups. Walk the track once yourself, then adapt. We don\'t replace your teaching authority.',
      deepenTitle: 'Ready to go deeper?',
      deepenBody: 'After the first 30 days, Bible100 offers backgrounds, book intros, and further reading. The track builds habit; depth can grow anytime.',
      cta: 'Start with Today →',
      howtoLink: 'How does it work?',
    },
    vi: {
      title: 'Tầm nhìn',
      lead: 'Chào bạn. Nếu được bạn bè giới thiệu—đừng lo, đây không phải lớp học nghiêm khắc.',
      p1: 'Mở Kinh Thánh đôi khi căng thẳng—sợ không hiểu, sợ theo không kịp. Đây là vài phút yên lặng mỗi ngày, không phải điểm danh.',
      p2: 'Không thi, không thuộc lòng ép buộc. Chỉ mời bạn 5 phút để Lời Chúa chạm vào đời sống.',
      p3: 'Bạn không đơn độc. Cùng nhau khích lệ—đọc chậm không bị loại, quên ngày không bị mắng.',
      bibleStoryTitle: 'Kinh Thánh có mạch truyện',
      bibleStoryBody: 'Kế hoạch 30 ngày đi qua sáng tạo, sa ngã, cứu rỗi, Hội thánh, tạo mới—not câu rời rạc. Các đoạn cân bằng Cựu/Tân Ước, tường thuật và thư, thơ ca và khôn ngoan.',
      versionsTitle: 'Bản dịch & đa ngôn ngữ',
      versionsBody: 'Hợp Nhất phồn thể, KJV, Việt 1934, Indonesia AYT… song song để gia đình đa ngôn ngữ cùng đọc một đoạn.',
      busyTitle: 'Cho người bận rộn',
      busyBody: '5 phút tập trung thường tốt hơn 1 giờ mệt mỏi. Mệt thì đọc ngắn. Quay lại là đủ.',
      promiseTitle: 'Lời hứa',
      promises: [
        'Từ khó? Hỏi đáp bằng lời đời thường.',
        'Cô đơn? Đội chạy—không xếp hạng.',
        'AI chỉ là bản nháp; hãy hỏi mục sư.',
        'Tiến độ trên máy bạn—không so sánh.',
      ],
      notTitle: 'Chúng tôi không làm',
      notList: [
        'Không bảng xếp hạng công khai',
        'Không dùng tội lỗi để ép bạn',
        'Không coi AI là giáo lý cuối',
      ],
      supplyTitle: 'Đường chạy & trạm tiếp tế',
      supplyBody: 'Đường chạy = thói quen hàng ngày. Bible100 = tra cứu sâu khi cần. Bắt đầu từ Hôm nay là đủ.',
      supplyLink: '→ Trạm Bible100',
      supplyUrl: 'https://bible100.lovestoblog.com/languages/index_vi.html',
      leaderTitle: 'Cho người dẫn dắt (giáo viên / mục sư)',
      leaderBody: 'Mỗi thử thách có Kinh văn, ứng dụng và lời cầu ngắn—dùng cho Chủ nhật hoặc nhóm nhỏ. Hãy đi một vòng trước, rồi điều chỉnh theo giảng dạy của bạn.',
      deepenTitle: 'Muốn đi sâu hơn?',
      deepenBody: 'Sau 30 ngày đầu, Bible100 có bối cảnh, giới thiệu sách và đọc thêm. Đường chạy xây thói quen; chiều sâu có thể thêm bất cứ lúc nào.',
      cta: 'Bắt đầu hôm nay →',
      howtoLink: 'Xem hướng dẫn?',
    },
    id: {
      title: 'Visi kami',
      lead: 'Halo. Jika teman mengajak Anda—tenang, ini bukan kelas yang menakutkan.',
      p1: 'Membuka Alkitab bisa menegangkan—takut tidak paham atau dihakimi. Ini adalah hening sebentar setiap hari, bukan absensi.',
      p2: 'Tanpa ujian hafalan. Hanya undangan 5 menit agar firman Tuhan menyentuh hidup nyata.',
      p3: 'Anda tidak sendiri. Saling menguatkan—lambat tidak dikucilkan; terlewat hari tidak dimarahi.',
      bibleStoryTitle: 'Alkitab punya alur cerita',
      bibleStoryBody: 'Rencana 30 hari melalui penciptaan, jatuh, penebusan, gereja, ciptaan baru—bukan kutipan acak. Ayat seimbang PL/ PB, narasi dan surat, puisi dan hikmat.',
      versionsTitle: 'Terjemahan & multibahasa',
      versionsBody: 'TC Union, KJV, Vietnam 1934, AYT Indonesia… berdampingan agar keluarga multibahasa membaca ayat yang sama.',
      busyTitle: 'Untuk yang sibuk',
      busyBody: '5 menit fokus sering lebih baik daripada 1 jam dengan rasa bersalah. Lelah? Baca pendek. Kembali? Itu sudah cukup.',
      promiseTitle: 'Janji kami',
      promises: [
        'Kata sulit? Tanya jawab dengan bahasa sederhana.',
        'Kesepian? Tim lari—tanpa peringkat.',
        'AI hanya draf; gembala tetap memimpin.',
        'Progres di perangkat Anda—tanpa membandingkan.',
      ],
      notTitle: 'Yang tidak kami lakukan',
      notList: [
        'Tidak ada papan peringkat publik',
        'Tidak memanfaatkan rasa bersalah',
        'Tidak menjadikan AI otoritas akhir',
      ],
      supplyTitle: 'Lintasan & pos bekalan',
      supplyBody: 'Lintasan = kebiasaan harian. Bible100 = studi & alat bila perlu. Mulai dari Hari ini sudah cukup.',
      supplyLink: '→ Pos bekalan Bible100',
      supplyUrl: 'https://bible100.lovestoblog.com/languages/index_id.html',
      leaderTitle: 'Untuk pemimpin (guru / gembala)',
      leaderBody: 'Setiap tantangan berisi ayat, aplikasi, dan doa singkat—untuk sekolah minggu atau kelompok kecil. Jalani lintasan sekali, lalu sesuaikan. Kami tidak menggantikan wewenang mengajar Anda.',
      deepenTitle: 'Ingin lebih dalam?',
      deepenBody: 'Setelah 30 hari pertama, Bible100 menawarkan latar, pengantar kitab, dan bacaan lanjutan. Lintasan membangun kebiasaan; kedalaman bisa ditambah kapan saja.',
      cta: 'Mulai hari ini →',
      howtoLink: 'Cara pakai?',
    },
  };

  function locale() {
    if (global.B100LocalePick && global.B100LocalePick.getLocale) {
      return global.B100LocalePick.getLocale();
    }
    var q = new URLSearchParams(location.search);
    return q.get('locale') || 'zh-Hant';
  }

  function pack(map) {
    return map[locale()] || map['zh-Hant'];
  }

  global.B100GuideContent = {
    howto: function () { return pack(HOWTO); },
    idea: function () { return pack(IDEA); },
    locale: locale,
  };
})(typeof window !== 'undefined' ? window : global);
